"""
15 realistic seed shipments for demo with geographic data
"""

SHIPMENTS = [
    # HIGH RISK (5 shipments)
    {
        "id": 1,
        "manifest_id": "MFN-2025-0001",
        "shipper_name": "Greenfield Industrial Trading Co., Ltd.",
        "shipper_country": "VN",
        "shipper_city": "Ho Chi Minh City",
        "shipper_lat": 10.7624,
        "shipper_lon": 106.6840,
        "consignee_name": "SunPath Energy Distributors LLC",
        "consignee_country": "US",
        "consignee_city": "Newark, NJ",
        "consignee_lat": 40.7282,
        "consignee_lon": -74.1740,
        "commodity_code": "7604.10",
        "commodity_name": "Aluminum Extrusions",
        "declared_value": 847500,
        "risk_score": 91,
        "h1_risk_level": "CRITICAL",
        "h2_signals": ["ISF_MISMATCH", "AIS_DWELL_ANOMALY"],
        "h3_recommendation": "EXAMINE",
        "status": "EXAMINE",
    },
    {
        "id": 2,
        "manifest_id": "MFN-2025-0002",
        "shipper_name": "Sunward Electronics Ltd.",
        "shipper_country": "VN",
        "shipper_city": "Da Nang",
        "shipper_lat": 16.0544,
        "shipper_lon": 108.2022,
        "consignee_name": "TechFlow Imports Inc.",
        "consignee_country": "US",
        "consignee_city": "Los Angeles, CA",
        "consignee_lat": 34.0522,
        "consignee_lon": -118.2437,
        "commodity_code": "8541.40",
        "commodity_name": "Electronic Components",
        "declared_value": 652300,
        "risk_score": 87,
        "h1_risk_level": "CRITICAL",
        "h2_signals": ["PRICE_BELOW_MARKET"],
        "h3_recommendation": "EXAMINE",
        "status": "EXAMINE",
    },
    {
        "id": 3,
        "manifest_id": "MFN-2025-0003",
        "shipper_name": "Pacific Trade Solutions",
        "shipper_country": "VN",
        "shipper_city": "Hai Phong",
        "shipper_lat": 20.8449,
        "shipper_lon": 106.6881,
        "consignee_name": "West Coast Manufacturing",
        "consignee_country": "US",
        "consignee_city": "Long Beach, CA",
        "consignee_lat": 33.7701,
        "consignee_lon": -118.1937,
        "commodity_code": "8483.30",
        "commodity_name": "Machinery Parts",
        "declared_value": 523400,
        "risk_score": 85,
        "h1_risk_level": "CRITICAL",
        "h2_signals": ["AIS_DWELL_ANOMALY"],
        "h3_recommendation": "EXAMINE",
        "status": "EXAMINE",
    },
    {
        "id": 4,
        "manifest_id": "MFN-2025-0004",
        "shipper_name": "Orient Logistics Co.",
        "shipper_country": "CN",
        "shipper_city": "Shanghai",
        "shipper_lat": 31.2304,
        "shipper_lon": 121.4737,
        "consignee_name": "Global Textiles Distribution",
        "consignee_country": "US",
        "consignee_city": "Charlotte, NC",
        "consignee_lat": 35.2271,
        "consignee_lon": -80.8431,
        "commodity_code": "6204.62",
        "commodity_name": "Textiles & Apparel",
        "declared_value": 445000,
        "risk_score": 82,
        "h1_risk_level": "CRITICAL",
        "h2_signals": ["SHIPPER_AGE_CONCERN"],
        "h3_recommendation": "EXAMINE",
        "status": "EXAMINE",
    },
    {
        "id": 5,
        "manifest_id": "MFN-2025-0005",
        "shipper_name": "Mekong Exports Ltd.",
        "shipper_country": "VN",
        "shipper_city": "Can Tho",
        "shipper_lat": 10.0379,
        "shipper_lon": 105.7869,
        "consignee_name": "European Steel Trading GmbH",
        "consignee_country": "DE",
        "consignee_city": "Hamburg",
        "consignee_lat": 53.5511,
        "consignee_lon": 9.9937,
        "commodity_code": "7226.91",
        "commodity_name": "Steel Products",
        "declared_value": 734200,
        "risk_score": 80,
        "h1_risk_level": "HIGH",
        "h2_signals": ["DOCUMENTATION_GAP"],
        "h3_recommendation": "EXAMINE",
        "status": "EXAMINE",
    },
    # MEDIUM RISK (5 shipments)
    {
        "id": 6,
        "manifest_id": "MFN-2025-0006",
        "shipper_name": "Solaria Manufacturing Sdn. Bhd.",
        "shipper_country": "MY",
        "shipper_city": "Petaling Jaya",
        "shipper_lat": 3.1957,
        "shipper_lon": 101.5244,
        "consignee_name": "SunPath Energy Distributors LLC",
        "consignee_country": "US",
        "consignee_city": "Dallas, TX",
        "consignee_lat": 32.7767,
        "consignee_lon": -96.7970,
        "commodity_code": "8541.40",
        "commodity_name": "Solar Modules",
        "declared_value": 892300,
        "risk_score": 52,
        "h1_risk_level": "MEDIUM",
        "h2_signals": [],
        "h3_recommendation": "REVIEW",
        "status": "WARN",
    },
    {
        "id": 7,
        "manifest_id": "MFN-2025-0007",
        "shipper_name": "TradePath Chemicals",
        "shipper_country": "TH",
        "shipper_city": "Bangkok",
        "shipper_lat": 13.7563,
        "shipper_lon": 100.5018,
        "consignee_name": "American Chemical Corp",
        "consignee_country": "US",
        "consignee_city": "Houston, TX",
        "consignee_lat": 29.7604,
        "consignee_lon": -95.3698,
        "commodity_code": "2901.10",
        "commodity_name": "Chemicals",
        "declared_value": 334500,
        "risk_score": 48,
        "h1_risk_level": "MEDIUM",
        "h2_signals": [],
        "h3_recommendation": "REVIEW",
        "status": "WARN",
    },
    {
        "id": 8,
        "manifest_id": "MFN-2025-0008",
        "shipper_name": "Global Access Trading",
        "shipper_country": "JP",
        "shipper_city": "Tokyo",
        "shipper_lat": 35.6762,
        "shipper_lon": 139.6503,
        "consignee_name": "North American Auto Parts",
        "consignee_country": "US",
        "consignee_city": "Detroit, MI",
        "consignee_lat": 42.3314,
        "consignee_lon": -83.0458,
        "commodity_code": "8708.30",
        "commodity_name": "Auto Parts",
        "declared_value": 567800,
        "risk_score": 45,
        "h1_risk_level": "MEDIUM",
        "h2_signals": [],
        "h3_recommendation": "REVIEW",
        "status": "WARN",
    },
    {
        "id": 9,
        "manifest_id": "MFN-2025-0009",
        "shipper_name": "CrossBorder Plastics",
        "shipper_country": "CN",
        "shipper_city": "Shenzhen",
        "shipper_lat": 22.5431,
        "shipper_lon": 114.0579,
        "consignee_name": "Canadian Plastic Imports",
        "consignee_country": "CA",
        "consignee_city": "Toronto, ON",
        "consignee_lat": 43.6629,
        "consignee_lon": -79.3957,
        "commodity_code": "3916.90",
        "commodity_name": "Plastic Materials",
        "declared_value": 278900,
        "risk_score": 42,
        "h1_risk_level": "LOW",
        "h2_signals": [],
        "h3_recommendation": "APPROVE",
        "status": "OK",
    },
    {
        "id": 10,
        "manifest_id": "MFN-2025-0010",
        "shipper_name": "Direct Import Solutions",
        "shipper_country": "MY",
        "shipper_city": "Kuala Lumpur",
        "shipper_lat": 3.1390,
        "shipper_lon": 101.6869,
        "consignee_name": "European Industrial Group",
        "consignee_country": "DE",
        "consignee_city": "Berlin",
        "consignee_lat": 52.5200,
        "consignee_lon": 13.4050,
        "commodity_code": "4001.29",
        "commodity_name": "Rubber Products",
        "declared_value": 423600,
        "risk_score": 40,
        "h1_risk_level": "LOW",
        "h2_signals": [],
        "h3_recommendation": "APPROVE",
        "status": "OK",
    },
    # LOW RISK (5 shipments)
    {
        "id": 11,
        "manifest_id": "MFN-2025-0011",
        "shipper_name": "TrustTrade Corporation",
        "shipper_country": "JP",
        "shipper_city": "Osaka",
        "shipper_lat": 34.6937,
        "shipper_lon": 135.5023,
        "consignee_name": "Premium Electronics USA",
        "consignee_country": "US",
        "consignee_city": "San Jose, CA",
        "consignee_lat": 37.3382,
        "consignee_lon": -121.8863,
        "commodity_code": "8517.62",
        "commodity_name": "Electronics",
        "declared_value": 689200,
        "risk_score": 18,
        "h1_risk_level": "LOW",
        "h2_signals": [],
        "h3_recommendation": "APPROVE",
        "status": "OK",
    },
    {
        "id": 12,
        "manifest_id": "MFN-2025-0012",
        "shipper_name": "DirectCorp Trading",
        "shipper_country": "TH",
        "shipper_city": "Chiang Mai",
        "shipper_lat": 18.7883,
        "shipper_lon": 98.9853,
        "consignee_name": "Canadian Food Imports Ltd",
        "consignee_country": "CA",
        "consignee_city": "Vancouver, BC",
        "consignee_lat": 49.2827,
        "consignee_lon": -123.1207,
        "commodity_code": "0809.10",
        "commodity_name": "Agricultural Products",
        "declared_value": 156400,
        "risk_score": 22,
        "h1_risk_level": "LOW",
        "h2_signals": [],
        "h3_recommendation": "APPROVE",
        "status": "OK",
    },
    {
        "id": 13,
        "manifest_id": "MFN-2025-0013",
        "shipper_name": "SafeShip Logistics",
        "shipper_country": "SG",
        "shipper_city": "Singapore",
        "shipper_lat": 1.3521,
        "shipper_lon": 103.8198,
        "consignee_name": "US Packaging Solutions",
        "consignee_country": "US",
        "consignee_city": "Atlanta, GA",
        "consignee_lat": 33.7490,
        "consignee_lon": -84.3880,
        "commodity_code": "4819.10",
        "commodity_name": "Packaging Materials",
        "declared_value": 234500,
        "risk_score": 15,
        "h1_risk_level": "LOW",
        "h2_signals": [],
        "h3_recommendation": "APPROVE",
        "status": "OK",
    },
    {
        "id": 14,
        "manifest_id": "MFN-2025-0014",
        "shipper_name": "Global Trade Partners",
        "shipper_country": "AU",
        "shipper_city": "Melbourne",
        "shipper_lat": -37.8136,
        "shipper_lon": 144.9631,
        "consignee_name": "American Minerals Inc.",
        "consignee_country": "US",
        "consignee_city": "Phoenix, AZ",
        "consignee_lat": 33.4484,
        "consignee_lon": -112.0742,
        "commodity_code": "2701.11",
        "commodity_name": "Minerals",
        "declared_value": 389700,
        "risk_score": 20,
        "h1_risk_level": "LOW",
        "h2_signals": [],
        "h3_recommendation": "APPROVE",
        "status": "OK",
    },
    {
        "id": 15,
        "manifest_id": "MFN-2025-0015",
        "shipper_name": "Prime Logistics Ltd.",
        "shipper_country": "NZ",
        "shipper_city": "Auckland",
        "shipper_lat": -37.0082,
        "shipper_lon": 174.7850,
        "consignee_name": "European Food Group",
        "consignee_country": "NL",
        "consignee_city": "Amsterdam",
        "consignee_lat": 52.3676,
        "consignee_lon": 4.9041,
        "commodity_code": "0811.90",
        "commodity_name": "Agricultural Products",
        "declared_value": 267800,
        "risk_score": 12,
        "h1_risk_level": "LOW",
        "h2_signals": [],
        "h3_recommendation": "APPROVE",
        "status": "OK",
    },
]
